name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Build
        shell: pwsh
        run: |
          pip install sphinx
          pip install solar-theme
          .\make.bat html
          .\make.bat singlehtml
      - name: Create html archive artifact
        shell: pwsh
        run: Copy-Item -Recurse .\build\html .\dfir-orc-doc
      - name: Upload archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: dfir-orc-doc.zip
          path: .\build\html
      - name: Create singlehtml archive artifact
        shell: pwsh
        run: Copy-Item -Recurse .\build\singlehtml .\build\dfir-orc-doc-singlehtml
      - name: Upload singlehtml archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: dfir-orc-doc-singlehtml.zip
          path: .\build\singlehtml\
      - name: Publish html pages
        if: github.ref == 'refs/heads/master'
        shell: pwsh
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          Move-Item build/html docs
          git add -f docs
          git commit -m "Update by GitHub Action"
          git reset --hard
          git clean -fdX
          git fetch origin
          git checkout gh-pages
          Remove-Item -Recurse -Force docs/
          git cherry-pick master -X theirs
          git push "https://${{ secrets.GITHUB_TOKEN }}@github.com/DFIR-ORC/dfir-orc.github.io.git" gh-pages
